# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import simulator
import datetime


class Ui_MainWindow(object):
    def __init__(self):
        self.sim = simulator.Simulator()
        self.sim.forever()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1185, 910)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainGridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.mainGridLayout.setObjectName("mainGridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabBar::tab{width:100}\n"
"QTabBar::tab{height:40}")
        self.tabWidget.setObjectName("tabWidget")
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.gridLayoutWidget = QtWidgets.QWidget(self.main)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 30, 261, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.travelerGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.travelerGridLayout.setContentsMargins(0, 0, 0, 0)
        self.travelerGridLayout.setObjectName("travelerGridLayout")
        self.nameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.travelerGridLayout.addWidget(self.nameLabel, 1, 0, 1, 1)
        self.idLabel1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.idLabel1.setFont(font)
        self.idLabel1.setObjectName("idLabel1")
        self.travelerGridLayout.addWidget(self.idLabel1, 3, 0, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.travelerGridLayout.addWidget(self.nameLineEdit, 3, 1, 1, 1)
        self.idLineEdit1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.idLineEdit1.setFont(font)
        self.idLineEdit1.setObjectName("idLineEdit1")
        self.travelerGridLayout.addWidget(self.idLineEdit1, 1, 1, 1, 1)
        self.infoLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(11)
        self.infoLabel.setFont(font)
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setObjectName("infoLabel")
        self.travelerGridLayout.addWidget(self.infoLabel, 0, 0, 1, 2)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.main)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(60, 170, 261, 111))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.InfoGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.InfoGridLayout.setContentsMargins(0, 0, 0, 0)
        self.InfoGridLayout.setObjectName("InfoGridLayout")
        self.destinationLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.destinationLabel.setFont(font)
        self.destinationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.destinationLabel.setObjectName("destinationLabel")
        self.InfoGridLayout.addWidget(self.destinationLabel, 2, 1, 1, 1)
        self.destinationCombo = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.destinationCombo.setFont(font)
        self.destinationCombo.setObjectName("destinationCombo")
        self.destinationCombo.addItem("")
        self.destinationCombo.addItem("")
        self.destinationCombo.addItem("")
        self.destinationCombo.addItem("")
        self.destinationCombo.addItem("")
        self.destinationCombo.addItem("")
        self.destinationCombo.addItem("")
        self.destinationCombo.addItem("")
        self.destinationCombo.addItem("")
        self.destinationCombo.addItem("")
        self.destinationCombo.addItem("")
        self.destinationCombo.addItem("")
        self.destinationCombo.addItem("")
        self.destinationCombo.addItem("")
        self.destinationCombo.addItem("")
        self.InfoGridLayout.addWidget(self.destinationCombo, 3, 1, 1, 1)
        self.travelLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(11)
        self.travelLabel.setFont(font)
        self.travelLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.travelLabel.setObjectName("travelLabel")
        self.InfoGridLayout.addWidget(self.travelLabel, 0, 0, 1, 2)
        self.originLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.originLabel.setFont(font)
        self.originLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.originLabel.setObjectName("originLabel")
        self.InfoGridLayout.addWidget(self.originLabel, 2, 0, 1, 1)
        self.originCombo = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.originCombo.setFont(font)
        self.originCombo.setObjectName("originCombo")
        self.originCombo.addItem("")
        self.originCombo.addItem("")
        self.originCombo.addItem("")
        self.originCombo.addItem("")
        self.originCombo.addItem("")
        self.originCombo.addItem("")
        self.originCombo.addItem("")
        self.originCombo.addItem("")
        self.originCombo.addItem("")
        self.originCombo.addItem("")
        self.originCombo.addItem("")
        self.originCombo.addItem("")
        self.originCombo.addItem("")
        self.originCombo.addItem("")
        self.originCombo.addItem("")
        self.InfoGridLayout.addWidget(self.originCombo, 3, 0, 1, 1)
        self.strategyLabel = QtWidgets.QLabel(self.main)
        self.strategyLabel.setGeometry(QtCore.QRect(140, 320, 91, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(11)
        self.strategyLabel.setFont(font)
        self.strategyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.strategyLabel.setObjectName("strategyLabel")
        self.hourSpin = QtWidgets.QSpinBox(self.main)
        self.hourSpin.setGeometry(QtCore.QRect(200, 400, 61, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.hourSpin.setFont(font)
        self.hourSpin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.hourSpin.setMaximum(23)
        self.hourSpin.setObjectName("hourSpin")
        self.daySpin = QtWidgets.QSpinBox(self.main)
        self.daySpin.setGeometry(QtCore.QRect(120, 400, 61, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.daySpin.setFont(font)
        self.daySpin.setMaximum(6)
        self.daySpin.setObjectName("daySpin")
        self.timeLimitLabel = QtWidgets.QLabel(self.main)
        self.timeLimitLabel.setGeometry(QtCore.QRect(70, 410, 41, 16))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.timeLimitLabel.setFont(font)
        self.timeLimitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLimitLabel.setObjectName("timeLimitLabel")
        self.startButton = QtWidgets.QPushButton(self.main)
        self.startButton.setGeometry(QtCore.QRect(130, 460, 111, 41))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.routeLabel = QtWidgets.QLabel(self.main)
        self.routeLabel.setGeometry(QtCore.QRect(150, 530, 72, 15))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(11)
        self.routeLabel.setFont(font)
        self.routeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.routeLabel.setObjectName("routeLabel")
        self.routeTextBrowser = QtWidgets.QTextBrowser(self.main)
        self.routeTextBrowser.setGeometry(QtCore.QRect(10, 560, 381, 281))
        self.routeTextBrowser.setObjectName("routeTextBrowser")
        self.strategyRadioButton1 = QtWidgets.QRadioButton(self.main)
        self.strategyRadioButton1.setGeometry(QtCore.QRect(70, 360, 101, 19))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.strategyRadioButton1.setFont(font)
        self.strategyRadioButton1.setObjectName("strategyRadioButton1")
        self.strategyRadioButton2 = QtWidgets.QRadioButton(self.main)
        self.strategyRadioButton2.setGeometry(QtCore.QRect(180, 360, 131, 19))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.strategyRadioButton2.setFont(font)
        self.strategyRadioButton2.setObjectName("strategyRadioButton2")
        self.tabWidget.addTab(self.main, "")
        self.log = QtWidgets.QWidget()
        self.log.setObjectName("log")
        self.logGridLayout = QtWidgets.QGridLayout(self.log)
        self.logGridLayout.setObjectName("logGridLayout")
        self.logLabel = QtWidgets.QLabel(self.log)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(11)
        self.logLabel.setFont(font)
        self.logLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logLabel.setObjectName("logLabel")
        self.logGridLayout.addWidget(self.logLabel, 0, 1, 1, 1)
        self.stateSearchLabel = QtWidgets.QLabel(self.log)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(11)
        self.stateSearchLabel.setFont(font)
        self.stateSearchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stateSearchLabel.setObjectName("stateSearchLabel")
        self.logGridLayout.addWidget(self.stateSearchLabel, 2, 1, 1, 1)
        self.idLabel2 = QtWidgets.QLabel(self.log)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.idLabel2.setFont(font)
        self.idLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.idLabel2.setObjectName("idLabel2")
        self.logGridLayout.addWidget(self.idLabel2, 4, 0, 1, 1)
        self.idLineEdit2 = QtWidgets.QLineEdit(self.log)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.idLineEdit2.setFont(font)
        self.idLineEdit2.setObjectName("idLineEdit2")
        self.logGridLayout.addWidget(self.idLineEdit2, 4, 1, 1, 1)
        self.stateSearchButton = QtWidgets.QPushButton(self.log)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.stateSearchButton.setFont(font)
        self.stateSearchButton.setObjectName("stateSearchButton")
        self.logGridLayout.addWidget(self.stateSearchButton, 4, 2, 1, 1)
        self.stateSearchTextBrowser = QtWidgets.QTextBrowser(self.log)
        self.stateSearchTextBrowser.setObjectName("stateSearchTextBrowser")
        self.logGridLayout.addWidget(self.stateSearchTextBrowser, 3, 1, 1, 1)
        self.logTextBrowser = QtWidgets.QTextBrowser(self.log)
        self.logTextBrowser.setMaximumSize(QtCore.QSize(1500, 16777215))
        self.logTextBrowser.setObjectName("logTextBrowser")
        self.logGridLayout.addWidget(self.logTextBrowser, 1, 1, 1, 1)
        self.logGridLayout.setColumnStretch(0, 1)
        self.logGridLayout.setColumnStretch(1, 6)
        self.logGridLayout.setColumnStretch(2, 1)
        self.logGridLayout.setRowStretch(0, 1)
        self.logGridLayout.setRowStretch(1, 10)
        self.logGridLayout.setRowStretch(2, 1)
        self.logGridLayout.setRowStretch(3, 1)
        self.logGridLayout.setRowStretch(4, 1)
        self.tabWidget.addTab(self.log, "")
        self.mainGridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        # my
        self.daySpin.setEnabled(False)
        self.hourSpin.setEnabled(False)
        self.strategyRadioButton1.setChecked(True)
        self.strategyRadioButton2.toggled.connect(self.daySpin.setEnabled)
        self.strategyRadioButton2.toggled.connect(self.hourSpin.setEnabled)
        self.startButton.clicked.connect(self.startButton_clicked)
        # my
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "COVID-19安全旅行模拟系统"))
        self.nameLabel.setText(_translate("MainWindow", "    姓名:"))
        self.idLabel1.setText(_translate("MainWindow", "身份证号:"))
        self.infoLabel.setText(_translate("MainWindow", "旅客信息"))
        self.destinationLabel.setText(_translate("MainWindow", "目的地"))
        self.destinationCombo.setCurrentText(_translate("MainWindow", "北京"))
        self.destinationCombo.setItemText(0, _translate("MainWindow", "北京"))
        self.destinationCombo.setItemText(1, _translate("MainWindow", "天津"))
        self.destinationCombo.setItemText(2, _translate("MainWindow", "石家庄"))
        self.destinationCombo.setItemText(3, _translate("MainWindow", "济南"))
        self.destinationCombo.setItemText(4, _translate("MainWindow", "太原"))
        self.destinationCombo.setItemText(5, _translate("MainWindow", "郑州"))
        self.destinationCombo.setItemText(6, _translate("MainWindow", "合肥"))
        self.destinationCombo.setItemText(7, _translate("MainWindow", "南京"))
        self.destinationCombo.setItemText(8, _translate("MainWindow", "上海"))
        self.destinationCombo.setItemText(9, _translate("MainWindow", "西安"))
        self.destinationCombo.setItemText(10, _translate("MainWindow", "武汉"))
        self.destinationCombo.setItemText(11, _translate("MainWindow", "重庆"))
        self.destinationCombo.setItemText(12, _translate("MainWindow", "成都"))
        self.destinationCombo.setItemText(13, _translate("MainWindow", "杭州"))
        self.destinationCombo.setItemText(14, _translate("MainWindow", "兰州"))
        self.travelLabel.setText(_translate("MainWindow", "旅程信息"))
        self.originLabel.setText(_translate("MainWindow", "出发地"))
        self.originCombo.setItemText(0, _translate("MainWindow", "北京"))
        self.originCombo.setItemText(1, _translate("MainWindow", "天津"))
        self.originCombo.setItemText(2, _translate("MainWindow", "石家庄"))
        self.originCombo.setItemText(3, _translate("MainWindow", "济南"))
        self.originCombo.setItemText(4, _translate("MainWindow", "太原"))
        self.originCombo.setItemText(5, _translate("MainWindow", "郑州"))
        self.originCombo.setItemText(6, _translate("MainWindow", "合肥"))
        self.originCombo.setItemText(7, _translate("MainWindow", "南京"))
        self.originCombo.setItemText(8, _translate("MainWindow", "上海"))
        self.originCombo.setItemText(9, _translate("MainWindow", "西安"))
        self.originCombo.setItemText(10, _translate("MainWindow", "武汉"))
        self.originCombo.setItemText(11, _translate("MainWindow", "重庆"))
        self.originCombo.setItemText(12, _translate("MainWindow", "成都"))
        self.originCombo.setItemText(13, _translate("MainWindow", "杭州"))
        self.originCombo.setItemText(14, _translate("MainWindow", "兰州"))
        self.strategyLabel.setText(_translate("MainWindow", "策略选择"))
        self.hourSpin.setSuffix(_translate("MainWindow", "时"))
        self.daySpin.setSuffix(_translate("MainWindow", "天"))
        self.timeLimitLabel.setText(_translate("MainWindow", "限时:"))
        self.startButton.setText(_translate("MainWindow", "开始模拟"))
        self.routeLabel.setText(_translate("MainWindow", "旅行路线"))
        self.strategyRadioButton1.setText(_translate("MainWindow", "最少风险"))
        self.strategyRadioButton2.setText(_translate("MainWindow", "限时最少风险"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main), _translate("MainWindow", "模拟旅行"))
        self.logLabel.setText(_translate("MainWindow", "系统日志"))
        self.stateSearchLabel.setText(_translate("MainWindow", "旅客状态查询"))
        self.idLabel2.setText(_translate("MainWindow", "身份证号:"))
        self.stateSearchButton.setText(_translate("MainWindow", "开始查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log), _translate("MainWindow", "日志"))

    def show_route(self, name, ID):
        d_date, risk, route = self.sim.get_plan(ID)
        text = ''
        one_day = datetime.timedelta(days=1)
        prev = int(d_date.strftime('%H'))
        E2C = {'BUS': '汽车', 'TRAIN': '火车', 'AIRPLANE': '飞机'}
        text += f'{name}，您好！\n\n'
        if len(route) > 0:
            text += f'为您规划的最佳路线如下：\n'
            for part in route:
                if part['origin'] == part['destination']:
                    continue
                else:
                    if part['departure_time'] < prev:
                        d_date += one_day
                    text += f"{d_date.strftime('%m-%d')} {part['departure_time']:02} - "
                    if part['arrival_time'] < part['departure_time']:
                        d_date += one_day
                    text += f"{d_date.strftime('%m-%d')} {part['arrival_time']:02}  " \
                            f"{part['origin']} --> {part['destination']}  {E2C[part['type']]}\n"
            text += f"当前路线的风险值为：{risk}"
        else:
            text += f'非常抱歉，基于您当前的选择，系统无法为您找到合适的路线。'

        font = QtGui.QFont()
        font.setFamily("新宋体")
        # font.setPointSize(10)
        self.routeTextBrowser.setFont(font)
        self.routeTextBrowser.setText(text)

    def startButton_clicked(self):
        name = self.nameLineEdit.text()
        ID = self.idLineEdit1.text()
        if name == '' or ID == '':
            QtWidgets.QMessageBox.warning(self.centralwidget, '注意', '姓名和身份证号不能为空！',
                                          QtWidgets.QMessageBox.Ok, QtWidgets.QMessageBox.Ok)
        elif self.originCombo.currentText() == self.destinationCombo.currentText():
            QtWidgets.QMessageBox.warning(self.centralwidget, '注意', '出发地和目的地不能相同！',
                                          QtWidgets.QMessageBox.Ok, QtWidgets.QMessageBox.Ok)
        else:
            origin = self.originCombo.currentText()
            destination = self.destinationCombo.currentText()
            limit = self.strategyRadioButton2.isChecked()
            if limit:
                time_limit = int(self.daySpin.text()[:-1]) * 24 + int(self.hourSpin.text()[:-1])
            else:
                time_limit = 4 * 24  # TODO: 修改此处
            traveler = {'name': name, 'ID': ID, 'origin': origin, 'destination': destination, 'time_limit': time_limit}
            self.nameLineEdit.clear()
            self.idLineEdit1.clear()
            self.sim.new_traveler(traveler)
            self.show_route(name, ID)

    def stateSearchButton_clicked(self):
        if ID == '':
            QtWidgets.QMessageBox.warning(self.centralwidget, '注意', '身份证号不能为空！',
                                          QtWidgets.QMessageBox.Ok, QtWidgets.QMessageBox.Ok)
        else:
            pass
